// Message
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
// Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const GET_SECURITY_QUESTION = 'GET_SECURITY_QUESTION';
export const GET_SECURITY_QUESTION_FAIL = 'GET_SECURITY_QUESTION_FAIL';
export const VALIDATE_SECURITY_ANSWER = 'VALIDATE_ANSWER';
// Club
export const GET_POLLS = 'POLLS_LOADING';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const GET_SHARED_ACCESS = 'GET_SHARED_ACCESS';
// Library
export const HOLD_REQUEST_SUCCESS = 'HOLD_REQUEST_SUCCESS';
export const LOAD_RECENTS = 'LOAD_RECENTS';
export const GET_ALL_SERIES = 'GET_ALL_SERIES';
export const GET_SINGLE_SERIES = 'GET_SINGLE_SERIES';
export const GET_SINGLE_SERIES_FAIL = 'GET_SINGLE_SERIES_FAIL';
