"""
Django settings for tamanga_club project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from .base import *

SECRET_KEY = os.environ.get('SECRET_KEY')

ALLOWED_HOSTS = [os.environ.get('ALLOWED_HOSTS')]

DEBUG = False

WSGI_APPLICATION = 'tamanga_club.wsgi.prod.application'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
DEFAULT_STORAGE = "django_s3_storage.storage.S3Storage"
STATICFILES_STORAGE = "django_s3_storage.storage.StaticS3Storage"

# AWS SETTINGS
# The AWS region to connect to.
AWS_REGION = "us-east-1"
# The AWS access key to use.
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# The AWS secret access key to use.
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
# The name of the bucket to store files in.
AWS_S3_BUCKET_NAME = os.environ.get("AWS_BUCKET_NAME")
AWS_S3_BUCKET_NAME_STATIC = os.environ.get("AWS_STATIC_BUCKET_NAME")
AWS_S3_KEY_PREFIX = 'media'

django_heroku.settings(locals())
