# Generated by Django 3.0.4 on 2020-05-22 06:09


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(
                    max_length=255, unique=True, verbose_name='Title')),
                ('series_author', models.CharField(blank=True,
                                                   max_length=255, null=True, verbose_name='Author')),
                ('series_artist', models.CharField(blank=True,
                                                   max_length=255, null=True, verbose_name='artist')),
                ('series_genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), (
                    'misc', 'Miscellaneous'), ('slice_of_life', 'Slice of Life'), ('yoai', 'Yoai'), ('yuri', 'Yuri')], default='Misc', max_length=30, verbose_name='Genre')),
                ('series_sub_genre', models.CharField(blank=True, choices=[('boys_love', 'Boys Love'), (
                    'girls_love', 'Girls Love'), ('isekai', 'Isekai')], max_length=30, null=True, verbose_name='Sub Genre')),
                ('series_cover_image', models.ImageField(blank=True,
                                                         null=True, upload_to='', verbose_name='Series Cover Image')),
                ('complete', models.BooleanField(default=False,
                                                 verbose_name='Is this series completed?')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(
                    default=0, verbose_name='Volume number')),
                ('cover_image', models.ImageField(blank=True,
                                                  null=True, upload_to='', verbose_name='Cover Image')),
                ('available', models.BooleanField(
                    default=True, verbose_name='Availabe')),
                ('loaned_to', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Series')),
            ],
        ),
    ]
