# Generated by Django 3.0.4 on 2020-03-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='status',
            new_name='complete',
        ),
    ]
