# Generated by Django 3.0.4 on 2020-03-25 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_auto_20200325_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='loaned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='series',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
    ]
