# Generated by Django 3.0.4 on 2020-03-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200323_0151'),
        ('catalogue', '0002_auto_20200323_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='User',
        ),
    ]
