# Generated by Django 3.0.4 on 2020-03-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_user_admin'),
    ]

    operations = [
    ]
