# Generated by Django 3.0.4 on 2020-04-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_book_series'),
        ('catalogue', '0002_auto_20200419_0021'),
    ]

    operations = [
    ]
