# Generated by Django 3.0.7 on 2020-07-08 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
