# Generated by Django 3.0.7 on 2020-07-02 02:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200623_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='series_sub_genres',
        ),
        migrations.AlterField(
            model_name='series',
            name='series_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('misc', 'Miscellaneous'), ('slice_of_life', 'Slice of Life'), ('yoai', 'Yoai'), ('yuri', 'Yuri'), ('boys_love', 'Boys Love'), ('girls_love', 'Girls Love'), ('isekai', 'Isekai')], default=True, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
