# Generated by Django 3.0.7 on 2020-07-10 03:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_auto_20200708_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='club.Message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='club.Thread')),
            ],
        ),
    ]
