# Generated by Django 3.0.7 on 2020-07-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200710_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='club',
            field=models.ForeignKey(default='New Group', on_delete=django.db.models.deletion.CASCADE, to='club.BookClub'),
            preserve_default=False,
        ),
    ]
