# Generated by Django 3.0.7 on 2020-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20200615_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(default='Is it wrong to put random defaults in a dungeon?', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(default="What's your favorite anime?", max_length=255),
        ),
    ]
